### ISSUE TITLE
Blocklist support

### ISSUE THREAD

**Issue by 097115** [sweetbbak/tget#4]
It could add another layer of security if `tget` would support specifying a blocklist, either via a local file, or, even more broadly, via an URL, like, for instance, `transmission` does.

**Comment by sweetbbak** [comment]
Sure, thats a good idea, I'll add it to the roadmap. Should be fairly easy too

**Comment by sweetbbak** [comment]
and done! So far I just implemented plain text non-packed IP blocklists that aren't compressed but I will consider doing that. I also want to just make a fully featured torrent client so I might just refactor so things are more modular and clean over the weekend.
