### ISSUE TITLE
A `--version` switch would be useful

### ISSUE THREAD

**Issue by kseistrup** [sweetbbak/tget#5]
Please provide a `-V`/`--version` switch that prints the executable's name and version (and possibly version date) to standard output and exits successfully.

E.g.:

```sh
» tget --version
tget v0.1 (2024-03-20)
```

Such a switch is useful for:

+ users or admins who want to know if an upgrade is needed, or when
+ referring to a given version when submitting a bug report (the submitter may not be the one who installed the binary).

PS: I suggest using a capital `-V` for the short option. That way the lowercase `-v` is still available for a potentially future option that will be used more frequently (e.g., `--verbose`) than the version switch.

:pray:

**Comment by sweetbbak** [comment]
Great idea, I usually do this but overlooked it. I added it and pushed it in [2dfe89b](https://github.com/sweetbbak/tget/commit/2dfe89ba846d70e250844cc4e9fc329e39b758b8)

Thanks for the feedback!

**Comment by kseistrup** [comment]
Thanks!
