### ISSUE TITLE
[FYI] Now available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [sweetbbak/tget#7]
[ This message is purely informational, no action is necessary on your part, and you can close this “issue” at your discretion. ]

Tget is now available from AUR as `tget-git`:

* https://aur.archlinux.org/packages/tget-git

It can be installed using an [AUR helper](https://wiki.archlinux.org/title/AUR_helpers), e.g.:

```sh
yay -S tget-git
```

:pray:

**Comment by sweetbbak** [comment]
Awesome! Thank you
